{% set name = "omero-py" %}
{% set version = "5.19.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 974e835fa2e26def25c6cdac4440db721fe9ac24f6df1da3f1d6af96d89d288d

build:
  entry_points:
    - omero=omero.main:main
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  noarch: python

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - appdirs
    - future
    - matplotlib-base
    - numpy <2
    - pillow
    - portalocker
    - python >=3.6
    - pywin32-on-windows
    - pyyaml
    - requests
    - urllib3 <2
    - zeroc-ice >=3.6.5,<3.7

test:
  imports:
    - omero
    - omero.api
    - omero.clients
    - omero.cmd
    - omero.constants
    - omero.fs
    - omero.gateway
    - omero.grid
    - omero.install
    - omero.metadatastore
    - omero.model
    - omero.plugins
    - omero.romio
    - omero.sys
    - omero.util
    - omero_ext
  commands:
    - pip check
    - omero --help
  requires:
    - pip

about:
  home: https://www.openmicroscopy.org/
  license: GPL-2.0-or-later
  license_family: GPL2
  license_file: LICENSE.txt
  summary: Python bindings to the OMERO.blitz server
  doc_url: https://docs.openmicroscopy.org/latest/omero/developers
  dev_url: https://github.com/ome/omero-py

extra:
  recipe-maintainers:
    - goanpeca
    - joshmoore
    - jburel
