{% set name = "omero-py" %}
{% set version = "5.19.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 9c9b7e3af5257cce6ac5f296f6673bbe7bb1f5ed9776c81b96142b61a1b73ed2

build:
  entry_points:
    - omero=omero.main:main
  script: {{ PYTHON }} -m pip install . -vv
  number: 1
  noarch: python

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - appdirs
    - future
    - matplotlib-base
    - numpy <2
    - pillow
    - portalocker
    - python >={{ python_min }}
    - pywin32-on-windows
    - pyyaml
    - requests
    - urllib3 <2
    - zeroc-ice >=3.6.5,<3.7

test:
  imports:
    - omero
    - omero.api
    - omero.clients
    - omero.cmd
    - omero.constants
    - omero.fs
    - omero.gateway
    - omero.grid
    - omero.install
    - omero.metadatastore
    - omero.model
    - omero.plugins
    - omero.romio
    - omero.sys
    - omero.util
    - omero_ext
  commands:
    - pip check
    - omero --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://www.openmicroscopy.org/
  license: GPL-2.0-or-later
  license_family: GPL2
  license_file: LICENSE.txt
  summary: Python bindings to the OMERO.blitz server
  doc_url: https://docs.openmicroscopy.org/latest/omero/developers
  dev_url: https://github.com/ome/omero-py

extra:
  recipe-maintainers:
    - goanpeca
    - joshmoore
    - jburel
